### ISSUE TITLE
Crash when I am around crops

### ISSUE THREAD

**Issue by MCJediYoda** [EdwinMindcraft/SeasonsAPI#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  SeasonsPreLoader (SeasonsAPI-1.1.2a.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  CCCDeobfPlugin (unknown)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 5/3/16 8:42 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:beetroots, properties=[age]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at mod.mindcraft.seasons.WorldHandler.onCropsUpdate(WorldHandler.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_162_WorldHandler_onCropsUpdate_CropsUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
     **at mod.mindcraft.seasons.api.utils.EventUtils.postCropUdate**(EventUtils.java:13)
    at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:71)
    at net.minecraft.block.BlockBeetroot.func_180650_b(SourceFile:53)
    at net.minecraft.block.Block.func_180645_a(Block.java:447)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:468)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at mod.mindcraft.seasons.WorldHandler.onCropsUpdate(WorldHandler.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_162_WorldHandler_onCropsUpdate_CropsUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at mod.mindcraft.seasons.api.utils.EventUtils.postCropUdate(EventUtils.java:13)
    at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:71)
    at net.minecraft.block.BlockBeetroot.func_180650_b(SourceFile:53)
    at net.minecraft.block.Block.func_180645_a(Block.java:447)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:468)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)

-- Affected level --
Details:
    Level name: MCJediYoda
    All players: 1 total; [EntityPlayerMP['MCJediYoda'/70, l='MCJediYoda', x=-135.84, y=65.00, z=-303.77]]
    Chunk stats: ServerChunkCache: 979 Drop: 0
    Level seed: 2923147640224997602
    Level generator: ID 06 - RTG, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 89869 game time, 154550 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 51716 (now: false), thunder time: 43338 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 511379416 bytes (487 MB) / 2373451776 bytes (2263 MB) up to 3612868608 bytes (3445 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3876m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
    FML: MCP 9.23 Powered by Forge 12.16.0.1882 62 mods loaded, 61 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1882-1.9.jar) 
    UCHIJAAAA   Forge{12.16.0.1882} [Minecraft Forge](forge-1.9-12.16.0.1882-1.9.jar) 
    UCHIJAAAA   CodeChickenCore{2.0.1.53} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   moreexfoodppp{1.1.0} [MrDimka's More Extra Food]([1.9] MoreExtraFood+++ - 1.1.0.jar) 
    UCHIJAAAA   JEI{3.3.3.197} [Just Enough Items](jei_1.9-3.3.3.197.jar) 
    UCHIJAAAA   abyssalcraft{1.9.1.4} [AbyssalCraft](AbyssalCraft-1.9-1.9.1.4.jar) 
    UCHIJAAAA   acblocks{1.0.0} [AbyssalBlocks](AbyssalBlocks-1.9-1.0.0.jar) 
    UCHIJAAAA   bagginses{2.3.0b} [Bagginses](Bagginses-1.9-2.3.0b.jar) 
    UCHIJAAAA   Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UCHIJAAAA   BaublesHud{2.3.0} [Baubles-Hud](BaublesHud-1.9-2.3.0.jar) 
    UCHIJAAAA   baublesstuff{2.0.6} [Baubles Stuff](baublesstuff-2.0.6.jar) 
    UCHIJAAAA   BBG{4.0.0} [BetterBedrockGen](BetterBedrockGenerator-1.9.0-3.0.0.jar) 
    UCHIJAAAA   betterbuilderswands{0.6.0} [Better Builder's Wands](BetterBuildersWands-0.6.0-1.9r124+c748dee.jar) 
    UCHIJAAAA   bookshelf{1.2.0.226} [Bookshelf](Bookshelf-1.9-1.2.0.237.jar) 
    UCHIJAAAA   bookshelfapi{3.0.4} [Bookshelf](Bookshelf-API-1.9-3.0.4.jar) 
    UCHIJAAAA   Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCHIJAAAA   ChickenChunks{2.0.1.26} [ChickenChunks](ChickenChunks-1.9-2.0.1.26-universal.jar) 
    UCHIJAAAA   CustomMainMenu{2.0} [Custom Main Menu](CustomMainMenu-MC1.9-2.0.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9.jar) 
    UCHIJAAAA   DarkUtils{1.1.0.32} [Dark Utilities](DarkUtilities-1.9-1.1.0.33.jar) 
    UCHIJAAAA   elementsofpower{0.7.6-alpha} [Elements of Power](ElementsOfPower-1.9-0.7.6-alpha.jar) 
    UCHIJAAAA   endercompass{1.2.3} [Ender Compass](EnderCompass-1.9-1.2.3.jar) 
    UCHIJAAAA   enderutilities{0.5.3} [Ender Utilities](enderutilities-1.9-0.5.3.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.9-1.6.jar) 
    UCHIJAAAA   harvestchevsky{b5} [Gentle Harvest](Gentle_Harvest_1.9_b5.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.34} [LunatriusCore](LunatriusCore-1.9-1.1.2.34-universal.jar) 
    UCHIJAAAA   InGameInfoXML{2.8.1.83} [InGame Info XML](InGameInfoXML-1.9-2.8.1.83-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.61-dev-49-c5b6395} [Inventory Tweaks](InventoryTweaks-1.61-dev-49.jar) 
    UCHIJAAAA   IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHIJAAAA   journeymap{1.9-5.2.0b1} [JourneyMap](journeymap-1.9-5.2.0b1-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.5.24} [Just Enough Resources](JustEnoughResources-1.9-0.4.5.24.jar) 
    UCHIJAAAA   JET{1.2.28} [JustEnoughTooltips](JustEnoughTooltips-1.9-1.2.28.jar) 
    UCHIJAAAA   malisiscore{1.9-3.0.6} [MalisisCore](malisiscore-1.9-3.0.6.jar) 
    UCHIJAAAA   malisisdoors{1.9-4.0.1} [MalisisDoors](malisisdoors-1.9-4.0.1.jar) 
    UCHIJAAAA   mantle{1.9-0.10.0.jenkins132} [Mantle](Mantle-1.9-0.10.0.jar) 
    UCHIJAAAA   modifiable_armor{2.0.1} [Modifiable Armor 2](Modifiable-Armor-1.0.1.jar) 
    UCHIJAAAA   modularsystems{3.0.2} [Modular Systems](ModularSystems-1.9-3.0.2.jar) 
    UCHIJAAAA   morefood{1.15b} [More Foods](morefood-1.9-1854-1.15b.jar) 
    UCHIJAAAA   moreoverlays{1.2} [MoreOverlays](moreoverlays-1.2-mc1.9.jar) 
    UCHIJAAAA   MouseTweaks{2.6.2} [Mouse Tweaks](MouseTweaks-2.6.2-mc1.9.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.2-5.jar) 
    UCHIJAAAA   tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct](TConstruct-1.9-2.3.0.jar) 
    UCHIJAAAA   neotech{3.0.6} [NeoTech](NeoTech-1.9-3.0.6.jar) 
    UCHIJAAAA   netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9-3.0.6.jar) 
    UCHIJAAAA   notenoughwands{1.3.2} [Not Enough Wands](notenoughwands-1.9.0-1.3.2.jar) 
    UCHIJAAAA   packingtape{0.5.1} [Packing Tape](Packing Tape-0.5.1.jar) 
    UCHIJAAAA   placemod{2.2} [Placemod](Placemod-2.2-1.9.jar) 
    UCHIJAAAA   reborncore{2.1.0.53} [RebornCore](RebornCore-1.9-2.1.0.53-universal.jar) 
    UCHIJAAAA   refinedstorage{0.4.1} [Refined Storage](refinedstorage-0.4.1.jar) 
    UCHIJAAAA   ResourceLoader{1.5} [Resource Loader](ResourceLoader-MC1.9-1.5.jar) 
    UCHIJAAAA   rftools{4.46} [RFTools](rftools-1.9.0-4.46.jar) 
    UCHIJAAAA   Roguelike{1.5.0} [Roguelike Dungeons](RoguelikeDungeons-1.9-1.5.0.jar) 
    UCHIJAAAA   RTG{1.9-0.0.5} [Realistic Terrain Generation](RTG-1.9-0.0.5.jar) 
    UCHIJAAAA   seasonsapi{1.1.2a} [Seasons API](SeasonsAPI-1.1.2a.jar) 
    UCHIJAAAA   StorageDrawers{1.9-3.1.6} [Storage Drawers](StorageDrawers-1.9-3.1.6.jar) 
    UCHIJAAAA   tombstone{1.1} [Tombstone](tombstone-1.2.0.jar) 
    UCHIJAAAA   Trashcans{2.0.2} [Trashcans](Trashcans-1.9-2.0.2.jar) 
    UCHIJAAAA   VeinMiner{0.31.5_build.forgePost18010} [Vein Miner](VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support](VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UD  seasonsAPIPreloader{Seasons API Preloader} [Seasons API Preloader](minecraft.jar) 
    Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
SeasonsPreLoader (SeasonsAPI-1.1.2a.jar)
  mod.mindcraft.seasons.asm.Transformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)

MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)

```
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['MCJediYoda'/70, l='MCJediYoda', x=-135.84, y=65.00, z=-303.77]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by EdwinMindcraft** [comment]
I didn't know beetroot used a special grow system...

**Comment by EdwinMindcraft** [comment]
1.1.3 is out, bug is fixed

**Comment by MCJediYoda** [comment]
Thank you for the quick fix !!
