### ISSUE TITLE
1.8.9-Crash when entering a dimension

### ISSUE THREAD

**Issue by WenXin20** [EdwinMindcraft/SeasonsAPI#3]
v1.0.3 
Crash when entering the dimension in Aroma's Dimension Mod
http://pastebin.com/EJPqcT7L

**Comment by EdwinMindcraft** [comment]
I'll fix it but 1.0.X are 1.8.9. I won't do support to much on those version

**Comment by EdwinMindcraft** [comment]
I'll release 1.0.3a in a few minutes

**Comment by WenXin20** [comment]
Ok, thanks
